# export before `ray start`
export PYTHONHASHSEED=10000
export HYDRA_FULL_ERROR=1
export VLLM_ATTENTION_BACKEND=XFORMERS
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

N_GPUS_PER_NODE=8
N_NODES=1
LOGGER=''

ENV=sokoban
DATA_PATH=dataset/$ENV
MODEL_NAME=Qwen2.5-7B
MODEL_PATH=/home/yangxiaobo/my_data/models/$MODEL_NAME
PROJ_NAME=agent-zero
EXP_NAME=debug-$ENV-$MODEL_NAME-PPO_$(date +%Y%m%d_%H%M%S)
LOG_FILE_PATH=log/$EXP_NAME
mkdir -p $LOG_FILE_PATH

N_AGENTS=1
MAX_TURNS=3
MAX_VAL_TURNS=1
TURNS_MAXIMUM=$(( MAX_TURNS > MAX_VAL_TURNS ? MAX_TURNS : MAX_VAL_TURNS ))
MAX_PROMPT_LENGTH=2048
MAX_RESPONSE_LENGTH=800
MAX_FEEDBACK_LENGTH=200
TRAIN_BATCH_SIZE=8
MINI_BATCH_SIZE=8
MICRO_BATCH_SIZE_PER_GPU=1
TOTAL_LENGTH=$(($MAX_PROMPT_LENGTH+($MAX_RESPONSE_LENGTH+$MAX_FEEDBACK_LENGTH)*$TURNS_MAXIMUM))

python -m src.core.main_ppo \
    data.train_files=$DATA_PATH/train.parquet \
    data.val_files=$DATA_PATH/test.parquet \
    +data.log_dir=$LOG_FILE_PATH \
    data.train_batch_size=$TRAIN_BATCH_SIZE \
    data.max_prompt_length=$TOTAL_LENGTH \
    data.max_response_length=$MAX_RESPONSE_LENGTH \
    +data.max_feedback_length=$MAX_FEEDBACK_LENGTH \
    +data.max_turns=$MAX_TURNS \
    +data.val_max_turns=$MAX_VAL_TURNS \
    data.shuffle=False \
    +data.reward_allocate_method=step \
    +debug.check_token_align=true \
    actor_rollout_ref.hybrid_engine=True \
    actor_rollout_ref.model.path=$MODEL_PATH \
    actor_rollout_ref.model.override_config={} \
    actor_rollout_ref.model.enable_gradient_checkpointing=False \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.strategy=fsdp \
    actor_rollout_ref.actor.ppo_mini_batch_size=$MINI_BATCH_SIZE \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=$MICRO_BATCH_SIZE_PER_GPU \
    actor_rollout_ref.actor.use_dynamic_bsz=False \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=16384 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.actor.clip_ratio=0.2 \
    actor_rollout_ref.actor.entropy_coeff=0.001 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.ppo_epochs=1 \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.actor.optim.lr=3e-7 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.0 \
    actor_rollout_ref.actor.optim.min_lr_ratio=None \
    actor_rollout_ref.actor.optim.warmup_style=constant \
    actor_rollout_ref.actor.optim.total_training_steps=-1 \
    actor_rollout_ref.actor.fsdp_config.wrap_policy.min_num_params=0 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.actor.fsdp_config.fsdp_size=-1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    actor_rollout_ref.ref.fsdp_config.wrap_policy.min_num_params=0 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.temperature=0.5 \
    actor_rollout_ref.rollout.top_k=-1 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.dtype=bfloat16 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.ignore_eos=False \
    actor_rollout_ref.rollout.enforce_eager=True \
    actor_rollout_ref.rollout.free_cache_engine=True \
    actor_rollout_ref.rollout.load_format=dummy_dtensor \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.max_num_batched_tokens=$TOTAL_LENGTH \
    actor_rollout_ref.rollout.max_num_seqs=1024 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.do_sample=True \
    +actor_rollout_ref.rollout.n_agent=$N_AGENTS \
    critic.optim.lr=1e-5 \
    critic.model.use_remove_padding=True \
    critic.optim.lr_warmup_steps_ratio=0.015 \
    critic.model.path=$MODEL_PATH \
    critic.model.enable_gradient_checkpointing=true \
    critic.ppo_micro_batch_size=8 \
    algorithm.gamma=1.0 \
    algorithm.lam=1.0 \
    algorithm.adv_estimator=gae \
    algorithm.kl_ctrl.kl_coef=0.0 \
    algorithm.kl_penalty=kl \
    +algorithm.no_think_rl=False \
    +algorithm.state_masking.enable=True \
    trainer.total_epochs=30 \
    trainer.total_training_steps=300 \
    trainer.project_name=$PROJ_NAME \
    trainer.experiment_name=$EXP_NAME \
    trainer.logger=["$LOGGER"] \
    trainer.val_before_train=true \
    trainer.nnodes=$N_NODES \
    trainer.n_gpus_per_node=$N_GPUS_PER_NODE \
    trainer.save_freq=-1 \
    trainer.test_freq=10 \
    trainer.critic_warmup=0 \
    +env.name=$ENV \
    +env.dim_x=5 \
    +env.dim_y=5 \
    +env.num_boxes=1 \
    +env.search_depth=30 \
    2>&1 | tee $LOG_FILE_PATH/$EXP_NAME.log